name: CD
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: masterjanic/docker-compose-ssh-deployment@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          docker_compose_filename: compose.yaml